apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: test
spec:
  encryptedData:
    TEST: AgASDyKfzme+GxfKrkhiFpF5VO8WOhXMt9+3bS3AMPGibG1D3ap0vPxlHmXdJWjS7lezkkfNra6OVROaHKfw3dwvWeF86SzmmlRJhhRhu26cBx3QghuRwA/h8+gdklzxwHYdXlO2w9aPajn7gYLRXqtZ4nlgBc14Mh/mgXU/r6xFU2cT5F7zlW8baJtQcuKdXOX28b8ftQLqJ6rdYH7DUutyqqH86N4qlk32asHQySkj3jKV0uesjMb9UphdurAEUREObTedjnxuYj+BfuvOHsLyCaNaPnCKdlBUI+wsk3ELdNreXTzdG+Rp5pvL10w5Or1pKXzrk4g7D1ZVoxAIxptMNQlmFteKLmGQk1LqUjlnDySapTaqR5LLYqNjBzL/h9nyDQDQ8W5NgLFCvpOfwvu3bIzmUd10gBHLNxfv3szh21q2HLA3Gxs/Kj02fgT4QDJQnrIRGDwzwONF9iTl0V5KFVPJHreIuBTeosXUWLkpxZHZzFzDwNpQm6njJtTOsOy5z8duZoBkLuJyt0I3FV7qgQIl4h+Wu/1YgVCwUgPM7PS/rbCh2hWkrQ74YWzDzSNw9H31e+DCnzwbdhkSYQEaCVvgp8m3M+vttinv1yrJjiwa7bpEP68jXwyqW37mcq9b4xK4FRnhnf6ebDfi1KU4LlmlGFmnByTsx9vLpqpGO+v07jWIk3nLc5CydM2kXkoMm1y7R5g=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      name: test

